# Generated by Django 5.0.2 on 2024-03-01 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('serial_no', models.IntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=40)),
                ('author_name', models.CharField(max_length=20)),
                ('publisher', models.CharField(max_length=30)),
                ('dateofpub', models.DateField()),
            ],
        ),
    ]
